version: '3'

services: 
  app:
    build: 
      container_name: api-worldbank-proxy
      entrypoint: ./.docker/entrypoint.sh
      ports: 
        - 8080:3000
      volumes: 
        - .:/home/node/app
  